### ISSUE TITLE
Localization FR

### ISSUE THREAD

**Issue by tbzt** [toktic/sr_gmt#2]
Hello, thank you so much for your tool ! I've been looking for this kind of tool for some time and had started to make something for myself but nothing as precise and finely crafted. I'm in the process of translating it into French for my own local use, in compliance with your license. If you ever add a localization, I could offer to do the translation into French. This also applies to SR6. Again, congratulations and thanks for this work!

**Comment by toktic** [comment]
Internationalization can be a pain, especially when sentence structure gets involved. I view this tool as a hobby and do not currently expect to work on internationalization. But if that changes, I will keep you in mind. In case you hadn't seen it already, I have a version of this tool for SR6 here: https://github.com/toktic/sr6_gmt that I have updated more frequently.
